# Generated by Django 5.2.8 on 2026-01-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaljob',
            name='level',
            field=models.CharField(choices=[('GRADUATE', 'Graduate'), ('ENTRY', 'Entry-level'), ('INTERNSHIP', 'Internship')], default='GRADUATE', max_length=20),
        ),
    ]
