# Generated by Django 5.2.8 on 2026-03-19 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_jobs', '0002_alter_internaljob_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internaljob',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='internaljob',
            name='external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='internaljob',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ADZUNA', 'Adzuna')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='internaljob',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
