# Generated by Django 5.2.8 on 2026-03-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_jobs', '0003_internaljob_external_id_internaljob_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaljob',
            name='category',
            field=models.CharField(choices=[('SOFTWARE', 'Software'), ('DATA', 'Data'), ('AI_ML', 'AI / ML'), ('CYBER', 'Cybersecurity'), ('CLOUD_DEVOPS', 'Cloud / DevOps'), ('IT_SUPPORT', 'IT Support'), ('PRODUCT', 'Product'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='internaljob',
            name='external_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
