# Generated by Django 5.2.8 on 2026-04-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_jobs', '0004_internaljob_category_internaljob_external_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaljob',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ADZUNA', 'Adzuna'), ('REED', 'Reed')], default='MANUAL', max_length=20),
        ),
    ]
