# Generated by Django 5.2.8 on 2026-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
