# Generated by Django 5.2.8 on 2026-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
